app/blog/urls.py
# src/app/blog/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.blog import views

# app name
app_name = "blog"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("about/", views.about_view, name="about"),
    path("blogs/<int:category_id>/", views.blogs_by_category_view, name="posts_by_category"),
    path('blogs/<slug:slug>/', views.blogs_by_slug_view, name='blogs_by_slug'),

    # Search endpoint
    path("blog/search/", views.search_view, name="search"),
]

app/user/urls.py
# src/app/user/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.user import views

# app name
app_name = "user"

urlpatterns = [
    path("user/register/", views.register_view, name="register"),
    path("user/login/", views.login_view, name="login"),
    path("user/logout/", views.logout_view, name="logout"),
]

config/urls.py
# src/config/urls.py

# Django and third parties modules
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # user
    path("", include("app.user.urls", namespace="user")),
    
    # admin
    path("admin/", admin.site.urls),

    # blog
    path("", include("app.blog.urls", namespace="blog")),

    # dashboard
    path("", include("app.dashboard.urls", namespace="dashboard")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/models.py
# src/app/blog/models.py

# Django and third parties modules
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name



class Blog(models.Model):

    STATUS_CHOICES = (
        ("Draft", "Draft"),
        ("Published", "Published")
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150, unique=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    featured_image = models.ImageField(upload_to='uploads/%Y/%m/%d')
    short_description = models.TextField(max_length=500)
    blog_body = models.TextField(max_length=2000)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Draft")
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class About(models.Model):
    about_heading = models.CharField(max_length=25)
    about_description = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "About"

    def __str__(self):
        return self.about_heading


class SocialLink(models.Model):
    platform = models.CharField(max_length=25)
    link = models.URLField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.platform


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.TextField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

app/blog/views.py
# src/app/blog/views.py

# Django and third parties modules
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q

# Locals
from app.blog.models import Category, Blog, About, Comment

# Create your views here.

def home_view(request):
	
	# Select featured object dari Blog
	featured_posts = Blog.objects.filter(is_featured=True)

	# # Select semua blogs yang bukan featured dengan status published
	posts = Blog.objects.filter(is_featured=False, status="Published")

	# # Print objects untuk testing
	# # print(posts)

	data = {
		"featured_posts":featured_posts,
		"posts":posts
	}

	return render(request, "blog/index.html", data)



def blogs_by_category_view(request, category_id):
    
    # Fetch the blogs that belongs to a category identified by its category_id
    blogs_by_category = Blog.objects.filter(status='Published', category=category_id)

    # Gunakan try/except untuk tidak memperlihatkan warning LAMAN TIDAK DITEMUI bila category tidak ada
    try:
        category = Category.objects.get(pk=category_id)
    except:
        # redirect the user to homepage
        return redirect('blog:home')

    # # Use get_object_or_404 when you want to show 404 error page if the category does not exist
    # category = get_object_or_404(Category, pk=category_id)

    data = {
        "blogs_by_category": blogs_by_category,
        "category":category,
    }

    return render(request, 'blog/blogs_by_category.html', data)


def blogs_by_slug_view(request, slug):
    
    single_blog = get_object_or_404(Blog, slug=slug, status="Published")

    # Create comment
    if request.method == 'POST':
        comment = Comment()
        comment.user = request.user
        comment.blog = single_blog
        comment.comment = request.POST['comment']
        comment.save()
        return HttpResponseRedirect(request.path_info)

    # Comments
    comments = Comment.objects.filter(blog=single_blog)
    comment_count = comments.count()

    # testing
    # print("comment ==>", comments )

    data = {
        "single_blog":single_blog,
        "comments": comments,
        "comment_count":comment_count,
    }

    return render(request, 'blog/blogs_by_slug.html', data)


# src/app/blog/views.py
def about_view(request):

    about = About.objects.all()

    data = {
        "about":about
    }

    return render(request, 'blog/about.html', data)


def search_view(request):

    keyword = request.GET.get('keyword')
    
    # # Testing
    # print('this keyword', keyword)
    
    blogs = Blog.objects.filter(
        Q(title__icontains=keyword) | 
        Q(short_description__icontains=keyword) | 
        Q(blog_body__icontains=keyword), 
        status='Published')
  
    # Testing
    # print(blogs)

    data = {
        'blogs': blogs,
        'keyword': keyword,
    }

    return render(request, 'blog/search.html', data)

templates/blog/about.html
<!-- src/templates/blog/blogs_by_slug.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                {% for about in about %}
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{ about.about_heading }}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">
                        {{ about.created_at }}
                    </div>
                    <!-- Post category-->
                </header>
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{ about.about_description }}
                    </p>
                </section>
                {% endfor %}
            </article>
        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                        <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                    </div>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4 p-3">
                <h4 class="font-italic">Categories</h4>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                {% for category in categories %}
                                <li>
                                    <a href="{% url 'blog:posts_by_category' category.id %}">
                                    {{ category.category_name }}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4 p-3">
                <h4 class="font-italic">Follow Us</h4>
                <ol class="list-unstyled">
                    {% for social_link in social_links %}
                    <li>
                        <a href="{{ social_link.link }}" target="_blank">{{ social_link.platform }}</a>
                    </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/blog/blogs_by_category.html
<!-- src/templates/blog/blogs_by_category.html -->
{% extends 'base.html' %}

{% block content %}

<!-- Featured Posts -->
<h3 class="text-uppercase text-warning" style="letter-spacing: 2px;">Category - {{ category }}</h3>
<div class="row mb-2">

    {% if blogs_by_category %}

	    {% for blog_by_category in blogs_by_category %}
	    <div class="col-md-6">
	        <div class="card border-0" >
	            <div class="card-body">
	                <h3><a href="{% url 'blog:blogs_by_slug' blog_by_category.slug %}" class="text-dark">{{ blog_by_category.title }}</a></h3>
	                <small class="mb-1 text-muted">
	                	{{ blog_by_category.created_at | timesince }} ago | {{ blog_by_category.author }}
	                </small>
	                <p class="card-text">{{ blog_by_category.short_description | truncatewords:25 }}</p>
	            </div>
	        </div>
	    </div>
	    {% endfor %}

	    {% else %}
	    <div class="card-body">
		    <h3>Not found.</h3>
		    <p>Post yang dicari tidak ada.</p>
		</div>

    {% endif %}
</div>
</div>

{% endblock %}

templates/blog/blogs_by_slug.html
<!-- src/templates/blog/blogs_by_slug.html -->
{% extends 'base.html' %}

{% block content %}

<!-- Page content-->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">

                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{ single_blog.title }}</h1>

                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">
                    	Posted on {{ single_blog.created_at }} 
                    	by {{ single_blog.author }}</div>

                    <!-- Post category-->
                    <a 
                    	class="badge bg-primary text-decoration-none text-light" 
                    	href="#!">{{ single_blog.category }}
                    </a>
                </header>

                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" 
                	src="{{ single_blog.featured_image.url }}" alt="..." />
                </figure>

                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{ single_blog.short_description }}</p>
                    <p class="fs-5 mb-4">{{ single_blog.blog_body }}</p>

                    <!-- Comments -->
                    <h4>Komen: {{ comment_count }}</h4>

                    {% if comments %}
                        {% for comment in comments %}
                            <div class="card mt-1">
                                <div class="card-body">
                                    <p class="card-text mb-0">{{ comment }}</p>
                                    <span>
                                        <small>By {{ comment.user }}</small>
                                        <small>| {{ comment.created_at | timesince }} ago</small>
                                    </span>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        Belum ada komen
                    {% endif %}

                    <br>
                    <div class="form-group">
                        {% if user.is_authenticated %}
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <textarea name="comment" class="form-control" placeholder="Write your comment"></textarea>
                                <input type="submit" value="Submit" class="btn btn-primary mt-2">
                            </div>

                        </form>
                        {% else %}
                        <p>Please <span><a href="{% url 'user:login' %}">login</a></span> to write a comment!</p>
                        {% endif %}
                    </div>

                </section>
            </article>
        </div>

        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                        <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                    </div>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4 p-3">
                <h4 class="font-italic">Categories</h4>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                {% for category in categories %}
                                <li>
                                	<a href="{% url 'blog:posts_by_category' category.id %}">
                                	{{ category.category_name }}
                                	</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4 p-3">
                <h4 class="font-italic">Follow Us</h4>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">LinkedIn</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/blog/index.html
<!-- src/templates/blog/index.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Featured posts -->
<h3 class="text-uppercase text-warning" style="letter-spacing: 2px;">Featured Posts</h3>
<div class="row mb-2">
    {% for post in featured_posts %}
        {% if not forloop.first %}
            <div class="col-md-6">
                <div class="card border-0" >
                    <div class="card-body">
                        <h3>
                            <a href="{% url 'blog:blogs_by_slug' post.slug %}" 
                            class="text-dark">{{ post.title }}
                            </a>
                        </h3>
                        <small class="mb-1 text-muted">
                            {{ post.created_at | timesince }} ago | {{ post.author }}
                        </small>
                        <p class="card-text">
                            {{ post.short_description | truncatewords:25 }}
                        </p>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}  
</div>
<!-- Featured posts end -->

<!-- Recent articles -->
<h3 class="text-uppercase text-warning" style="letter-spacing: 2px;">Recent Articles</h3>
<main role="main" class="container p-0">
    <div class="row">

        <!-- Main recent articles -->
        <div class="col-md-8 blog-main">
            {% for post in posts %}
            <div class="card border-0">
                <div class="card-body">
                    <h3> <a href="{% url 'blog:blogs_by_slug' post.slug %}" class="text-dark">{{ post.title }}</a></h3>
                    <small class="mb-1 text-muted">{{ post.created_at | timesince }} ago | {{ post.author }}</small>
                    <p class="card-text">{{ post.short_description | truncatewords:25 }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- Main recent articles end -->

        <!-- Aside -->
        <aside class="col-md-4 blog-sidebar">
            <div class="p-3 mb-3 bg-light rounded">
                <h4 class="font-italic"><a href="{% url 'blog:about' %}">About</a></h4>
                <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            </div>
            <div class="p-3">
                <h4 class="font-italic">Follow Us</h4>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">LinkedIn</a></li>
                </ol>
            </div>
        </aside>
        <!-- Aside end -->

    </div>
</main>
<!-- Recent articles end -->

{% endblock content %}

templates/blog/search.html
<!-- src/templates/blog/search.html -->

{% extends 'base.html' %}

{% block content %}

<h3 class="text-warning" 
    style="letter-spacing: 2px;">Search Term - <span style="color:#5A639C;">
    {{ keyword }}</span></h3>
<div class="row mb-2">
    {% if blogs %}
    {% for search in blogs %}
    <div class="col-md-6">
        <div class="card border-0" >
            <div class="card-body">
                <h3>
                    <a href="{% url 'blog:blogs_by_slug' search.slug %}" 
                        class="text-dark">{{ search.title }}
                    </a>
                </h3>
                <small 
                    class="mb-1 text-muted">
                    {{ search.created_at | timesince }} ago | {{ search.author }}</small>
                <p class="card-text">{{ search.short_description | truncatewords:25 }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="col-md-6">
        <h3>No posts found</h3>
        <p>Post yang dicari menggunakan <span style="color:#5A639C; font-style: italic; font-weight: bold;">
    {{ keyword }}</span> tidak ditemukan.</p>
    </div>
    {% endif %}
</div>

{% endblock content %}