app/blog/urls.py
# src/app/blog/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.blog import views

# app name
app_name = "blog"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("about/", views.about_view, name="about"),
    path("blogs/<int:category_id>/", views.blogs_by_category_view, name="posts_by_category"),
    path('blogs/<slug:slug>/', views.blogs_by_slug_view, name='blogs_by_slug'),

    # Search endpoint
    path("blog/search/", views.search_view, name="search"),
]

app/user/urls.py
# src/app/user/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.user import views

# app name
app_name = "user"

urlpatterns = [
    path("user/register/", views.register_view, name="register"),
    path("user/login/", views.login_view, name="login"),
    path("user/logout/", views.logout_view, name="logout"),
]

config/urls.py
# src/config/urls.py

# Django and third parties modules
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # user
    path("", include("app.user.urls", namespace="user")),
    
    # admin
    path("admin/", admin.site.urls),

    # blog
    path("", include("app.blog.urls", namespace="blog")),

    # dashboard
    path("", include("app.dashboard.urls", namespace="dashboard")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!-- src/templates/blog/index.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Blogs</title>
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="container">

        <!-- header -->
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-4 pt-1">
                    <a class="blog-header-logo text-dark" href="{% url 'blog:home' %}">Django Blog</a>
                </div>
                <div class="col-4">
                    <form action="{% url 'blog:search' %}" method="GET">
                        <div class="input-group">
                            <input 
                                class="form-control" 
                                type="text" 
                                name="keyword" 
                                value="" 
                                placeholder="Enter search term..." 
                                aria-label="Enter search term..." 
                                aria-describedby="button-search" />
                            <button 
                                type="submit" 
                                class="btn btn-warning" 
                                id="button-search" 
                                type="button">Go!</button>
                        </div>
                    </form>
                </div>

                <div class="col-4 d-flex justify-content-end align-items-center">
                    {% if not user.is_authenticated %}
                        <a class="btn btn-sm btn-warning" 
                            href="{% url 'user:login' %}">Login</a> &nbsp;
                        <a class="btn btn-sm btn-outline-secondary" 
                            href="{% url 'user:register' %}">Register</a>
                    {% else %}
                        <span style="padding-right: 15px;">{{ user|capfirst }}</span>
                        <a class="btn btn-sm btn-outline-secondary" 
                            href="{% url 'user:logout' %}">Logout</a>
                    {% endif %}
                </div>
                
            </div>
        </header>
        <!-- header end -->

        <!-- navbar -->
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
                <a class="p-2 text-muted" href="{% url 'blog:home' %}">Home</a>
                {% for category in categories %}
                <a class="p-2 text-muted" 
                    href="{% url 'blog:posts_by_category' category.id %}">
                    {{ category.category_name }}
                </a>
                {% endfor %}
            </nav>
        </div>
        <!-- navbar end -->

        <!-- hero featued post -->
        {% for featured_post in featured_posts %}
            {% if forloop.first %}
            <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark" 
                style="background-image: url({{ featured_post.featured_image.url }});
                background-blend-mode: overlay;background-size:cover;">
                <div class="col-md-8 px-0">
                    <h1 class="display-4 font-italic">{{ featured_post.title }}</h1>
                    <p class="lead my-3">{{ featured_post.short_description | truncatewords:25 }}</p>
                    <p class="lead mb-0">
                        <a 
                            href="{% url 'blog:blogs_by_slug' featured_post.slug %}" 
                            class="text-white font-weight-bold">
                            Continue reading...
                        </a>
                    </p>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        <!-- hero featued post end -->

        <!-- content -->
        {% block content %}
        {% endblock content %}
        <!-- content end -->

    </div>

    <!-- footer -->
    <footer class="blog-footer">
        <hr />
        <p style="text-align: center;">Developed with <span style="color:red;">love</span> by <span style="color:#0056B3;">ING</span> in <a href="#">Practical Skill_Sets</a></p>
    </footer>
    <!-- footer end -->

</body>
</html>