app/blog/urls.py
# src/app/blog/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.blog import views

# app name
app_name = "blog"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("about/", views.about_view, name="about"),
    path("blogs/<int:category_id>/", views.blogs_by_category_view, name="posts_by_category"),
    path('blogs/<slug:slug>/', views.blogs_by_slug_view, name='blogs_by_slug'),

    # Search endpoint
    path("blog/search/", views.search_view, name="search"),
]

app/dashboard/urls.py
# src/app/dashboard/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.dashboard import views

# app name
app_name = "dashboard"

urlpatterns = [
    path("dashboard/", views.dashboard_view, name="dashboard"),

    # crud categories
    path("dashboard/categories/", views.dashboard_category_view, name="dashboard_category"),
    path("dashboard/categories/add/", views.add_category_view, name="add_category"),
    path("dashboard/categories/edit/<int:pk>/", views.edit_category_view, name="edit_category"),
    path("dashboard/categories/delete/<int:pk>/", views.delete_category_view, name="delete_category"),

    # crud blogs
    path("dashboard/blogs/", views.dashboard_blog_view, name="dashboard_blog"),
    path("dashboard/blogs/add/", views.add_blog_view, name="add_blog"),
    path("dashboard/blogs/edit/<int:pk>/", views.edit_blog_view, name="edit_blog"),
    path("dashboard/blogs/delete/<int:pk>/", views.delete_blog_view, name="delete_blog"),

    # users
    path("dashboard/users/", views.dashboard_user_view, name="dashboard_user"),
    path("dashboard/users/add/", views.add_user_view, name="add_user"),
    path("dashboard/users/edit/<int:pk>/", views.edit_user_view, name="edit_user"),
    path("dashboard/users/delete/<int:pk>/", views.delete_user_view, name="delete_user"),
]

app/user/urls.py
# src/app/user/urls.py

# Django and third parties modules
from django.urls import path

# Locals
from app.user import views

# app name
app_name = "user"

urlpatterns = [
    path("user/register/", views.register_view, name="register"),
    path("user/login/", views.login_view, name="login"),
    path("user/logout/", views.logout_view, name="logout"),
]

config/urls.py
# src/config/urls.py

# Django and third parties modules
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # user
    path("", include("app.user.urls", namespace="user")),
    
    # admin
    path("admin/", admin.site.urls),

    # blog
    path("", include("app.blog.urls", namespace="blog")),

    # dashboard
    path("", include("app.dashboard.urls", namespace="dashboard")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/models.py
# src/app/blog/models.py

# Django and third parties modules
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name



class Blog(models.Model):

    STATUS_CHOICES = (
        ("Draft", "Draft"),
        ("Published", "Published")
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150, unique=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    featured_image = models.ImageField(upload_to='uploads/%Y/%m/%d')
    short_description = models.TextField(max_length=500)
    blog_body = models.TextField(max_length=2000)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Draft")
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class About(models.Model):
    about_heading = models.CharField(max_length=25)
    about_description = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "About"

    def __str__(self):
        return self.about_heading


class SocialLink(models.Model):
    platform = models.CharField(max_length=25)
    link = models.URLField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.platform


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.TextField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

app/dashboard/models.py
from django.db import models

# Create your models here.

app/dashboard/forms.py
# src/app/dashboard/forms.py

# Django and third parties modules
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Locals
from app.blog.models import Category, Blog


class CategoryForm(forms.ModelForm):
	
	class Meta:
		model = Category
		fields = '__all__'


class BlogForm(forms.ModelForm):
	class Meta:
		model = Blog
		fields = (
				'title', 'category', 'featured_image', 
				'short_description', 'blog_body', 'status', 
				'is_featured')


class AddUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = (
			'username', 'email', 'first_name', 
			'last_name', 'is_active', 'is_staff', 
			'is_superuser', 'groups', 'user_permissions')


class EditUserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = (
			'username', 'email', 'first_name', 
			'last_name', 'is_active', 'is_staff', 
			'is_superuser', 'groups', 'user_permissions')

app/user/forms.py
# src/app/user/forms.py

# Django and third parties modules
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):

	class Meta:
		model = User
		fields = ("email", "username", "password1", "password2")

app/blog/views.py
# src/app/blog/views.py

# Django and third parties modules
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q

# Locals
from app.blog.models import Category, Blog, About, Comment

# Create your views here.

def home_view(request):
	
	# Select featured object dari Blog
	featured_posts = Blog.objects.filter(is_featured=True)

	# # Select semua blogs yang bukan featured dengan status published
	posts = Blog.objects.filter(is_featured=False, status="Published")

	# # Print objects untuk testing
	# # print(posts)

	data = {
		"featured_posts":featured_posts,
		"posts":posts
	}

	return render(request, "blog/index.html", data)



def blogs_by_category_view(request, category_id):
    
    # Fetch the blogs that belongs to a category identified by its category_id
    blogs_by_category = Blog.objects.filter(status='Published', category=category_id)

    # Gunakan try/except untuk tidak memperlihatkan warning LAMAN TIDAK DITEMUI bila category tidak ada
    try:
        category = Category.objects.get(pk=category_id)
    except:
        # redirect the user to homepage
        return redirect('blog:home')

    # # Use get_object_or_404 when you want to show 404 error page if the category does not exist
    # category = get_object_or_404(Category, pk=category_id)

    data = {
        "blogs_by_category": blogs_by_category,
        "category":category,
    }

    return render(request, 'blog/blogs_by_category.html', data)


def blogs_by_slug_view(request, slug):
    
    single_blog = get_object_or_404(Blog, slug=slug, status="Published")

    # Create comment
    if request.method == 'POST':
        comment = Comment()
        comment.user = request.user
        comment.blog = single_blog
        comment.comment = request.POST['comment']
        comment.save()
        return HttpResponseRedirect(request.path_info)

    # Comments
    comments = Comment.objects.filter(blog=single_blog)
    comment_count = comments.count()

    # testing
    # print("comment ==>", comments )

    data = {
        "single_blog":single_blog,
        "comments": comments,
        "comment_count":comment_count,
    }

    return render(request, 'blog/blogs_by_slug.html', data)


# src/app/blog/views.py
def about_view(request):

    about = About.objects.all()

    data = {
        "about":about
    }

    return render(request, 'blog/about.html', data)


def search_view(request):

    keyword = request.GET.get('keyword')
    
    # # Testing
    # print('this keyword', keyword)
    
    blogs = Blog.objects.filter(
        Q(title__icontains=keyword) | 
        Q(short_description__icontains=keyword) | 
        Q(blog_body__icontains=keyword), 
        status='Published')
  
    # Testing
    # print(blogs)

    data = {
        'blogs': blogs,
        'keyword': keyword,
    }

    return render(request, 'blog/search.html', data)

app/dashboard/views.py
# src/app/dashboard/views.py

# Django and third parties modules
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Locals
from app.blog.models import Category, Blog
from app.dashboard.forms import CategoryForm, BlogForm, AddUserForm, EditUserForm

# Create your views here.

@login_required(login_url="user:login")
def dashboard_view(request):

	category_count = Category.objects.all().count()
	blog_count = Blog.objects.all().count()

	# Tesing
	# print(blog_count)

	data = {
		"category_count":category_count,
		"blog_count":blog_count
	}
	
	return render(request, "dashboard/dashboard.html", data)


def dashboard_category_view(request):

	category_count = Category.objects.all().count()

	data = {
		"category_count":category_count,
	}

	return render(request, "dashboard/categories.html", data)


def add_category_view(request):

	if request.method == "POST":

		form = CategoryForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect("dashboard:dashboard_category")
	
	else:
		form = CategoryForm()

	data = {
		"form":form
	}
	
	return render(request, "dashboard/add_category.html", data)

	
def edit_category_view(request, pk):

	category = get_object_or_404(Category, pk=pk)

	if request.method == 'POST':
		form = CategoryForm(request.POST, instance=category)
		if form.is_valid():
			form.save()
			return redirect("dashboard:dashboard_category")

	else:
		form = CategoryForm(instance=category)

	data = {
		'category': category,
		'form': form,
	}

	return render(request, "dashboard/edit_category.html", data)


def delete_category_view(request, pk):
	category = get_object_or_404(Category, pk=pk)
	category.delete()
	return redirect("dashboard:dashboard_category")


# ==================CRUD BLOGS=================


def dashboard_blog_view(request):

	blogs = Blog.objects.all()
	blog_count = Blog.objects.all().count()

	data = {
		'blogs': blogs,
		"blog_count":blog_count,
	}

	return render(request, "dashboard/blogs.html", data)


def add_blog_view(request):

	if request.method == 'POST':
		form = BlogForm(request.POST, request.FILES)
		if form.is_valid():
			blog = form.save(commit=False) # temporarily saving the form
			blog.author = request.user
			blog.save()
			title = form.cleaned_data['title']
			blog.slug = slugify(title) + '-'+str(blog.id)
			blog.save()
			return redirect("dashboard:add_blog")
		else:
			print('form is invalid')
			print(form.errors)

	else:
		form = BlogForm()

	data = {
		"form":form,
	}

	return render(request, "dashboard/add_blog.html", data)


def edit_blog_view(request, pk):

	blog = get_object_or_404(Blog, pk=pk)

	if request.method == 'POST':
		form = BlogForm(request.POST, request.FILES, instance=blog)
		if form.is_valid():
			blog = form.save()
			title = form.cleaned_data['title']
			blog.slug = slugify(title) + '-'+str(blog.id)
			blog.save()
			return redirect("blog:home")
	
	else:		
		form = BlogForm(instance=blog)

	data = {
		"form":form,
		"blog":blog,
	}

	return render(request, "dashboard/edit_blog.html", data)


def delete_blog_view(request, pk):
	blog = get_object_or_404(Blog, pk=pk)
	blog.delete()
	return redirect("dashboard:dashboard_blog")



# ==================USERS=================


def dashboard_user_view(request):

	users = User.objects.all()

	data = {
		"users":users,
	}
	
	return render(request, 'dashboard/users.html', data)


def add_user_view(request):

	if request.method == 'POST':
		form = AddUserForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect("dashboard:dashboard_user")
		else:
			print(form.errors)

	else:
		form = AddUserForm()

	data = {
		"form":form,
	}

	return render(request, 'dashboard/add_user.html', data)


def edit_user_view(request, pk):

	user = get_object_or_404(User, pk=pk)

	if request.method == 'POST':
		form = EditUserForm(request.POST, instance=user)
		if form.is_valid():
			form.save()
			return redirect("dashboard:dashboard_user")

	else:
		form = EditUserForm(instance=user)

	data = {
		"form":form,
	}

	return render(request, 'dashboard/edit_user.html', data)


def delete_user_view(request, pk):
	user = get_object_or_404(User, pk=pk)
	user.delete()
	return redirect("dashboard:dashboard_user")

app/user/views.py
# src/app/blog/views.py

# Django and third parties modules
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth 

# Locals
from app.user.forms import RegistrationForm

# Create your views here.

def register_view(request):

	"""RegistrationForm ini akan dirender
	saat user mengklik tombol register"""
	if request.method == "POST":
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect("user:register")

	else:
		"""RegistrationForm ini akan dirender saat
		user mengklik menu register"""
		form = RegistrationForm()

	data = {
		"form":form
	}

	return render(request, "user/register.html", data)


def login_view(request):

	"""AuthenticationForm ini akan dirender
	saat user mengklik TOMBOL login"""
	if request.method == "POST":
		form = AuthenticationForm(request, request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = auth.authenticate(username=username, password=password)
			if user is not None:
				auth.login(request, user)
			return redirect("dashboard:dashboard")

	else:
		"""AuthenticationForm ini akan dirender saat
		user mengklik MENU login"""
		form = AuthenticationForm()

	data = {
		"form":form
	}
	
	return render(request, "user/login.html", data)


def logout_view(request):
	auth.logout(request)
	return redirect("blog:home")

templates/dashboard/add_blog.html
<!-- src/templates/dashboard/add_blog.html -->

{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>Add New Post</h2>
        
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
    </div>
</div>

{% endblock %}

templates/dashboard/add_category.html
<!-- src/templates/dashboard/add_category.html -->

{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>Add New Category</h2>
        
        <form action="" method="POST" style="width:500px;">
        	{% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
    </div>
</div>

{% endblock %}

templates/dashboard/add_user.html
<!-- src/templates/dashboard/add_user.html -->

{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        {% if perms.auth.add_user %}
        <h2>Add New User</h2>
        
        <form action="{% url 'dashboard:add_user' %}" method="POST" >
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
        {% else %}
        <h5>Anda tidak memiliki izin untuk melihat halaman ini</h5>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/dashboard/blogs.html
<!-- src/templates/dashboard/blogs.html -->

{% extends 'base.html' %}


{% block content %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>All Posts</h2>
        <a href="{% url 'dashboard:add_blog' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>
        <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Title</th>
                <th>Category</th>
                <th>Author</th>
                <th>Status</th>
                <th>Featured</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
            {% for blog in blogs %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ blog.title }}</td>
                <td>{{ blog.category }}</td>
                <td>{{ blog.author }}</td>
                <td>{{ blog.status }}</td>
                <td>
                    {% if blog.is_featured %}
                        <i class="fa fa-check text-success"></i>
                    {% else %}
                        <i class="fa fa-times text-danger"></i>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'dashboard:edit_blog' blog.id %}"><i class="fa fa-edit text-success"></i></a>
                    &nbsp;
                    <a href="{% url 'dashboard:delete_blog' blog.id %}"><i class="fa fa-trash text-danger"></i></a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        {{ blog_count }} blog
    </div>
</div>

{% endblock %}

templates/dashboard/categories.html
<!-- src/templates/dashboard/categories.html -->

{% extends 'base.html' %}

{% block content %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>All Categories</h2>
        <a href="{% url 'dashboard:add_category' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Category Name</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            {% for cat in categories %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ cat }}</td>
                <td>{{ cat.created_at }}</td>
                <td>{{ cat.updated_at }}</td>
                <td>
                    <a 
                        href="{% url 'dashboard:edit_category' cat.id %}">
                        <i class="fa fa-edit text-success"></i></a>&nbsp;
                    <a href="{% url 'dashboard:delete_category' cat.id %}"><i class="fa fa-trash text-danger"></i></a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ category_count }} kategori
    </div>
</div>
{% endblock content %}

templates/dashboard/dashboard.html
<!-- src/templates/dashboard/dashboard.html -->

{% extends 'base.html' %}

{% block content %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <span>Logged in as <b>{{ user }}</b></span>
        <div class="row">
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center 
                    	text-uppercase font-weight-bold">All Categories</div>
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{ category_count }}</h5>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center 
                    	text-uppercase font-weight-bold">All posts</div>
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{ blog_count }}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/dashboard/edit_blog.html
<!-- src/templates/dashboard/edit_blog.html -->

{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>Edit Blog</h2>
        
        <form action="{% url 'dashboard:edit_blog' blog.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
    </div>
</div>

{% endblock %}

templates/dashboard/edit_category.html
<!-- src/templates/dashboard/edit_category.html -->

{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>Edit Category</h2>
        
        <form action="{% url 'dashboard:edit_category' category.id %}" method="POST" style="width:500px;">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
    </div>
</div>

{% endblock %}

templates/dashboard/edit_user.html
<!-- src/templates/dashboard/edit_user.html -->

{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>Edit User</h2>
        
        <form action="#" method="POST" >
        	{% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        <br>
        <h5>Anda tidak memiliki izin untuk melihat halaman ini</h5>
    </div>
</div>

{% endblock %}

templates/dashboard/left_sidebar.html
<!-- src/templates/dashboard/left_sidebar.html -->
	
	<div class="col-md-3">
	    <div class="nav flex-column nav-pills bg-light" aria-orientation="vertical">
			<a 
				href="{% url 'dashboard:dashboard' %}" 
				class="nav-link text-dark 
				{% if '/dashboard/' == request.path %} bg-warning {% endif %}">
				Dashboard</a>

			{% if perms.auth.view_user %}
	        	<a 
	        		href="{% url 'dashboard:dashboard_user' %}" 
	        		class="nav-link text-dark 
	        		{% if '/users/' in request.path %}bg-warning{% endif %}">
	        		Users
	        	</a>
        	{% endif %}

	        <a 
	        	href="{% url 'dashboard:dashboard_category' %}" 
	        	class="nav-link text-dark
	        	{% if '/categories/' in request.path %} bg-warning {% endif %}">
	        	Categories</a>
	        	
	        <a href="{% url 'dashboard:dashboard_blog' %}" 
	        	class="nav-link text-dark 
	        	{% if '/blogs/' in request.path %} bg-warning {% endif %} ">
	        	Blogs</a>

	        <a href="" class="nav-link text-dark">Logout</a>
	    </div>
	</div>

templates/dashboard/users.html
<!-- src/templates/dashboard/users.html -->

{% extends 'base.html' %}


{% block content %}

<div class="row">
    <!-- Left sidebar -->
    {% include 'dashboard/left_sidebar.html' %}

    <!-- Right side content -->
    <div class="col-md-9">
        <h2>All Users</h2>
        <a href="{% url 'dashboard:add_user' %}" class="btn btn-dark text-light float-right mb-2">Add User</a>
        <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Active</th>
                <th>Staff</th>
                <th>Superuser</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
            {% for user in users %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ user.first_name }} {{ user.last_name }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>
                    {% if user.is_active %}
                        <i class="fa fa-check text-success"></i>
                    {% else %}
                        <i class="fa fa-times text-danger"></i>
                    {% endif %}
                </td>
                <td>
                    {% if user.is_staff %}
                        <i class="fa fa-check text-success"></i>
                    {% else %}
                        <i class="fa fa-times text-danger"></i>
                    {% endif %}
                </td>
                <td>
                    {% if user.is_superuser %}
                        <i class="fa fa-check text-success"></i>
                    {% else %}
                        <i class="fa fa-times text-danger"></i>
                    {% endif %}
                </td>
                <td>
                    <a 
                        href="{% url 'dashboard:edit_user' user.id %}">
                        <i class="fa fa-edit text-success"></i></a>
                        &nbsp;
                    <a 
                        href="{% url 'dashboard:delete_user' user.id %}">
                        <i class="fa fa-trash text-danger"></i></a>
                </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
          <h5>Anda tidak memiliki izin untuk melihat halaman ini</h5>
    </div>
</div>

{% endblock %}